### ISSUE TITLE
预处理中关于pose的问题

### ISSUE THREAD

**Issue by Archer666** [muyouhang/Led3D#2]
你好！
    感谢公开论文代码，低质量3D人脸识别是一个很实际的问题。我在使用您提供的预处理代码时发现一个问题：Lock3Dface中一些带pose的人脸video在用您的代码预处理后会发生错误，本来应该得到一张侧面的人脸，但得到的结果是一些线条，例如
![003_PS_2_NMap_50](https://user-images.githubusercontent.com/36913946/77246093-e866d380-6c5e-11ea-91e8-4ef95498bebf.png)
这是Lock3Dface中003_Kinect_PS_2DEPTH这个video的第50帧的预处理结果，我完全按照您提供的代码运行的，这是否是由于Kinect得到的landmark有误差，导致鼻尖点位置选择错误

**Comment by muyouhang** [comment]
这是球面裁剪导致的问题。类似样本是有的，一般出现在大姿态人脸上；结果会受到：鼻尖点估计精度、裁剪半径和是否使用相机内参矫正深度图等影响。

**Comment by Archer666** [comment]
你好，请问论文中的预处理是否使用了相机内参矫正等调节方法？
此外，我用您的预处理代码做预处理之后，尝试复现论文中Table1的结果，出现两个问题：
1.在不做augmentation的情况下可以复现出论文中精度，但是做了augmentation精度反而下降，是否是我augmentation做的有问题，可以提供augmentation部分的代码吗？
2.在FE，PS，OC这三个subset上可以跑出79%等论文提供的精度，但在TM上我复现的精度非常低，只有百分之几。TM这个subset是否使用了和其他subset不一样的预处理吗？

**Comment by muyouhang** [comment]
数据预处理和扩增的方案都是一致的，没有针对TM的特别操作，数据预处理后TM的图变化应该不大，但存在模糊的现象。检查下TM的Label是不是给对了呢？

**Comment by Archer666** [comment]
你好，我仍然无法复现数据增强部分，文章在Shape Jittering部分，把均值为0方差为1e-5的高斯噪声加在了normalized point clouds上面，但文章并没有叙述什么是normalized point clouds，是直接加在了预处理后的点云上吗？还是进行了其他的操作，麻烦详细叙述一下，非常感谢

**Comment by Archer666** [comment]
方差是2e-5，不好意思写错了

**Comment by muyouhang** [comment]
噪声是加在Z上，Z进行了归一化，0-1之间。
