### ISSUE TITLE
这个人脸点云数据的组成有些疑问

### ISSUE THREAD

**Issue by Sheldongg** [muyouhang/Led3D#3]
点云数据可已从深度数据转换而成，也能用Rgb信息和深度数据合成。
所以在这里有些疑问，因为lock3dface数据集是RGBD格式的，而我希望最后人脸识别的时候只使用深度信息。请问最后进行测试过程中的点云数据，能否只用kinect3深度相机得来的点云数据进行人脸识别，而不是使用包含rgb的点云信息

**Comment by muyouhang** [comment]
当然是可以的。只要你的模型和数据匹配就可以了，而且led3d提供的预训练模型也是只使用了深度数据的。
