### ISSUE TITLE
论文复现

### ISSUE THREAD

**Issue by diggle1** [muyouhang/Led3D#5]
您好，我用您论文中的数据处理代码进行数据处理，发现不同裁剪半径带来很大的效果影响，而且对于NU，FE，TM等条件下的处理半径不同带来影响，想请教一下您对于每种情况下裁剪半径是多少。
对于每种情况，我使用一个比较适合的半径，同时我采用您的网络结构去训练，得到的结果与您论文中的结果相差比较大，您知道这是什么原因吗？

**Comment by muyouhang** [comment]
论文数据预处理阶段，只有TM是不同的裁剪半径，其他的NU\FE\OC\PS都是一样的。如果你觉着效果不理想，一个新的建议是根据人脸关键点进行人脸深度图像的分割提取。
训练结果如果差异较大，不知你有采用数据扩充的数据吗？ 是仅Led3D的结果差，还是多种网络都不好呢？需要排查数据或者训练两者问题。

**Comment by diggle1** [comment]
其他网络的结果没有跑，只跑了led3d的，所有设置和论文中的一样，采用了数据增强，想问一下TM裁剪半径，以及NU\FE\OC\PS裁剪半径是多少呢？

**Comment by muyouhang** [comment]
参照demo.m文件中的参数，TM比其他要略大一些，例如TM 120，NU 100这样的比例关系

**Comment by diggle1** [comment]
试过不同比例，但是效果仍不好。里面的那些没有脸部区域的训练和测试数据应该都没删除吧？您方便的话可不可分享下训练代码吗？

**Comment by Sheldongg** [comment]
同求训练代码

**Comment by muyouhang** [comment]
> 试过不同比例，但是效果仍不好。里面的那些没有脸部区域的训练和测试数据应该都没删除吧？您方便的话可不可分享下训练代码吗？

效果不好有绝对数值吗，是所有子集都不好，还是部分子集呢，可以贴出来结果看一下或者邮件联系我也行。

**Comment by diggle1** [comment]
> > 试过不同比例，但是效果仍不好。里面的那些没有脸部区域的训练和测试数据应该都没删除吧？您方便的话可不可分享下训练代码吗？
> 
> 效果不好有绝对数值吗，是所有子集都不好，还是部分子集呢，可以贴出来结果看一下或者邮件联系我也行。

![image](https://user-images.githubusercontent.com/38290717/138424263-303094c3-15f6-4858-9ca8-cef7638c7812.png)

**Comment by Sheldongg** [comment]
> > > 试过不同比例，但是效果仍不好。里面的那些没有脸部区域的训练和测试数据应该都没删除吧？您方便的话可不可分享下训练代码吗？
> > 
> > 
> > 效果不好有绝对数值吗，是所有子集都不好，还是部分子集呢，可以贴出来结果看一下或者邮件联系我也行。
> 
> ![image](https://user-images.githubusercontent.com/38290717/138424263-303094c3-15f6-4858-9ca8-cef7638c7812.png)

能看下你的训练代码嘛

**Comment by muyouhang** [comment]
> > > 试过不同比例，但是效果仍不好。里面的那些没有脸部区域的训练和测试数据应该都没删除吧？您方便的话可不可分享下训练代码吗？
> > 
> > 
> > 效果不好有绝对数值吗，是所有子集都不好，还是部分子集呢，可以贴出来结果看一下或者邮件联系我也行。
> 
> ![image](https://user-images.githubusercontent.com/38290717/138424263-303094c3-15f6-4858-9ca8-cef7638c7812.png)

看你对比的结果，是按照实验配置一进行的，avg=49的结果是偏低。文章中有提到，我们所有的模型都是在FRGC和Bosphorus上先“预训练“”，然后再使用Lock3DFace fintune，因为509个人的NU原始数据量太少了，哪怕加了数据扩增。
