### ISSUE TITLE
关于数据集划分

### ISSUE THREAD

**Issue by Ruizhuo-Xu** [muyouhang/Led3D#7]
你好，论文中提到把509个subject划分为340个subject作为训练集，169个subject作为测试集，请问是怎么划分的？或者能提供一下你们的划分结果吗？
另外一个问题是，训练时训练集中的每个视频是都等间隔截取6张图片参与训练还是只有中性表情截取6张图片参与增强，其他的视频所有的图片都参与训练呢？

**Comment by muyouhang** [comment]
1 0
2 1
3 2
4 3
8 4
9 5
10 6
11 7
12 8
13 9
14 10
15 11
16 12
18 13
19 14
20 15
21 16
22 17
24 18
25 19
26 20
27 21
28 22
29 23
30 24
32 25
33 26
34 27
35 28
36 29
37 30
39 31
40 32
41 33
42 34
43 35
44 36
45 37
46 38
47 39
48 40
49 41
50 42
51 43
52 44
53 45
54 46
55 47
56 48
57 49
58 50
59 51
60 52
61 53
62 54
63 55
64 56
65 57
66 58
67 59
68 60
69 61
70 62
71 63
73 64
74 65
75 66
76 67
78 68
79 69
80 70
81 71
82 72
83 73
84 74
85 75
86 76
87 77
88 78
89 79
90 80
91 81
92 82
93 83
94 84
95 85
97 86
98 87
99 88
100 89
102 90
104 91
105 92
106 93
107 94
108 95
109 96
110 97
111 98
112 99
113 100
114 101
115 102
116 103
117 104
118 105
119 106
120 107
121 108
122 109
123 110
124 111
125 112
126 113
127 114
128 115
129 116
131 117
133 118
134 119
135 120
136 121
137 122
138 123
999 124
139 125
140 126
141 127
142 128
143 129
144 130
145 131
147 132
149 133
150 134
151 135
152 136
153 137
154 138
155 139
156 140
157 141
158 142
159 143
160 144
166 145
167 146
168 147
169 148
170 149
171 150
172 151
176 152
177 153
178 154
179 155
180 156
181 157
182 158
183 159
184 160
185 161
186 162
187 163
188 164
189 165
190 166
191 167
192 168
193 169
194 170
195 171
196 172
197 173
199 174
201 175
202 176
203 177
204 178
205 179
206 180
207 181
208 182
210 183
211 184
212 185
213 186
214 187
215 188
216 189
217 190
218 191
221 192
222 193
224 194
225 195
227 196
228 197
229 198
230 199
231 200
232 201
233 202
234 203
235 204
236 205
237 206
238 207
239 208
243 209
244 210
245 211
246 212
247 213
249 214
250 215
251 216
252 217
253 218
254 219
255 220
256 221
257 222
258 223
259 224
260 225
261 226
262 227
263 228
264 229
265 230
266 231
267 232
268 233
269 234
270 235
271 236
272 237
273 238
274 239
275 240
276 241
277 242
278 243
279 244
280 245
281 246
282 247
283 248
284 249
285 250
286 251
287 252
288 253
289 254
290 255
291 256
292 257
293 258
294 259
295 260
296 261
297 262
298 263
299 264
300 265
301 266
302 267
303 268
304 269
305 270
306 271
307 272
308 273
309 274
310 275
311 276
312 277
313 278
314 279
315 280
316 281
317 282
318 283
319 284
320 285
321 286
322 287
323 288
324 289
325 290
326 291
327 292
328 293
329 294
330 295
331 296
332 297
333 298
334 299
335 300
336 301
337 302
338 303
339 304
340 305
341 306
342 307
343 308
344 309
345 310
346 311
347 312
348 313
349 314
350 315
351 316
352 317
353 318
354 319
355 320
356 321
357 322
358 323
359 324
360 325
361 326
362 327
363 328
364 329
365 330
366 331
367 332
368 333
369 334
370 335
371 336
372 337
373 338
374 339
375 340
376 341
377 342
378 343
379 344
380 345
381 346
382 347
383 348
384 349
385 350
386 351
387 352
388 353
389 354
390 355
391 356
392 357
393 358
394 359
395 360
396 361
397 362
398 363
399 364
400 365
401 366
402 367
403 368
404 369
405 370
406 371
407 372
408 373
409 374
410 375
411 376
412 377
413 378
414 379
415 380
416 381
417 382
418 383
419 384
420 385
421 386
422 387
423 388
424 389
425 390
426 391
457 392
458 393
459 394
460 395
461 396
462 397
463 398
464 399
465 400
466 401
467 402
468 403
469 404
470 405
471 406
472 407
473 408
475 409
476 410
477 411
478 412
480 413
481 414
482 415
483 416
485 417
486 418
487 419
488 420
489 421
490 422
491 423
492 424
493 425
494 426
495 427
496 428
497 429
498 430
499 431
500 432
501 433
502 434
503 435
504 436
505 437
506 438
507 439
508 440
509 441
510 442
511 443
512 444
513 445
514 446
515 447
516 448
517 449
518 450
519 451
520 452
521 453
522 454
523 455
524 456
525 457
526 458
527 459
528 460
529 461
530 462
531 463
532 464
533 465
534 466
535 467
536 468
537 469
538 470
539 471
540 472
541 473
542 474
543 475
544 476
545 477
546 478
427 479
428 480
429 481
430 482
431 483
432 484
433 485
434 486
435 487
436 488
437 489
438 490
439 491
440 492
441 493
442 494
443 495
444 496
445 497
446 498
447 499
448 500
449 501
450 502
451 503
452 504
453 505
454 506
455 507
456 508
601 506
602 477
603 484
604 491
605 437
606 498
609 12
610 32
612 485
613 475
614 487
615 508
616 483
617 480
618 486
619 482
620 495
621 501
622 124
623 404
624 412
625 11
626 463
628 398
629 399
630 396
631 394
632 395
633 502
634 401
635 400
636 499
637 392
638 393
639 415
640 225
641 226
642 227
643 228
644 231
645 232
646 230
647 229
648 233
649 234
650 237
651 239
652 240
653 236
654 235
655 238
656 242
657 244
658 246
659 245
660 248
661 243
662 247
663 249
664 250
665 251
666 252
667 253
668 256
669 254
670 241
671 255
672 257
673 223
674 221
675 217
676 258
677 220
678 224
679 219
680 218
681 222
682 332
683 369
684 334
685 333
686 335
687 350
688 349
689 351
690 315
691 314
692 316
693 317
694 318
695 362
696 319
697 361
698 341
699 340
700 375
701 385
702 391
703 357
704 326
705 372
706 373
707 371
708 374
709 348
710 347
711 353
712 383
713 364
714 367
715 365
716 339
717 323
718 325
719 322
720 324
721 327
722 321
723 338
724 336
725 308
726 309
727 307
728 306
729 313
730 263
731 264
732 266
733 267
734 265
735 312
736 310
737 311
738 271
739 273
740 270
741 276
742 274
743 275
744 284
745 283
746 285
747 282
748 287
749 286
750 288
751 289
752 294
753 303
754 293
755 290
756 300
757 295
758 298
759 296
760 297
761 299
762 304
763 302
764 301
765 346
766 330
767 354
768 390
769 328
770 384
771 358
772 476
773 5

**Comment by muyouhang** [comment]
please using this file, which can map subject to id:  https://drive.google.com/file/d/1BoxocqSLHdX3wpQh7EnFFY-MiGcxXRQh/view?usp=sharing
